excluded:
    .build

opt_in_rules:
    - force_unwrapping
    - opening_brace

force_unwrapping:
    severity: error

trailing_whitespace:
    severity: error

identifier_name:
    excluded:
        - id
        - ok
        - n
        - _navigationAction
        - _viewResolver
        - k

type_name:
    allowed_symbols:
        - _ViewResolver
        - _NavigationStack

large_tuple:
    warning: 9
    error: 16
